version: "3.8"

services:
  php_fpm:
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./../:/var/www/
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true client_host=host.docker.internal log_level=0'
    extra_hosts:
      - "host.docker.internal:host-gateway"


  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./../:/var/www:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm

  database:
    image: mysql:latest
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./dump:/var/dump
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${DATABASE_HOST_PORT}:3306

